// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJH3eCFCLu8gwVM7QGeyZugXcXLRwGLE4',
    appId: '1:536155230830:web:f177e736ff111ae1ed8c7f',
    messagingSenderId: '536155230830',
    projectId: 'ondrive-fe3fe',
    authDomain: 'ondrive-fe3fe.firebaseapp.com',
    databaseURL: 'https://ondrive-fe3fe-default-rtdb.firebaseio.com',
    storageBucket: 'ondrive-fe3fe.appspot.com',
    measurementId: 'G-DBBCEZ5V7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPyMQyxkluI5qdlfvkm65TmdubK11zs-I',
    appId: '1:536155230830:android:f2a6deb46719da4ded8c7f',
    messagingSenderId: '536155230830',
    projectId: 'ondrive-fe3fe',
    databaseURL: 'https://ondrive-fe3fe-default-rtdb.firebaseio.com',
    storageBucket: 'ondrive-fe3fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrKeN2lWcd98LKDwFOmak_h1AFemOhWU',
    appId: '1:536155230830:ios:e51c13f97f69bb05ed8c7f',
    messagingSenderId: '536155230830',
    projectId: 'ondrive-fe3fe',
    databaseURL: 'https://ondrive-fe3fe-default-rtdb.firebaseio.com',
    storageBucket: 'ondrive-fe3fe.appspot.com',
    iosBundleId: 'com.ondrive.driver',
  );
}
